package com.example.andre.calculadoraandroid;


import android.content.Context;
import android.content.Intent;
import android.database.Cursor;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.v4.app.LoaderManager;
import android.support.v4.content.CursorLoader;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.widget.CursorAdapter;

public class Ativityrecicler extends AppCompatActivity implements LoaderManager.LoaderCallbacks<Cursor>{

    private EconomiaCursorAdapter economiaCursorAdapter;
    private static final int CursorLoaderID = 0;
    public static final String ECONOMIA_ID="ECONOMIA_ID";
    private RecyclerView recyclerViewEconomia;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_ativityrecicler);

        recyclerViewEconomia = (RecyclerView) findViewById(R.id.RecyclerViewPrecos);

        recyclerViewEconomia.setLayoutManager(new LinearLayoutManager(this));

        economiaCursorAdapter = new EconomiaCursorAdapter(this);
        recyclerViewEconomia.setAdapter(economiaCursorAdapter);

        economiaCursorAdapter.setViewHolderClickListener(new View.OnClickListener() {
             @Override
             public void onClick(View view) {
                 editEconomia();
             }
        });
        getSupportLoaderManager().initLoader(CursorLoaderID, null, this);
    }

    private void editEconomia() {
        int id = economiaCursorAdapter.getLastEconomiaClicked();
        Intent intent = new Intent(this,EditEconomia.class);
        intent.putExtra(ECONOMIA_ID,id);
        startActivity(intent);
    }
    @Override
    protected void onResume() {
        super.onResume();
        getSupportLoaderManager().restartLoader(CursorLoaderID, null, this);
    }

    /**
     * Instantiate and return a new Loader for the given ID.
     * <p>
     * <p>This will always be called from the process's main thread.
     *
     * @param id   The ID whose loader is to be created.
     * @param args Any arguments supplied by the caller.
     * @return Return a new Loader instance that is ready to start loading.
     */
    @NonNull
    @Override
    public android.support.v4.content.Loader<Cursor> onCreateLoader(int id, @Nullable Bundle args) {
        if (id == CursorLoaderID) {
            return new CursorLoader(this, FuncoesContentProvider.FINANCA_URI, DbTabelaFinancas.All_colunas, null, null, null);
        }
       return null;
    }

    /**
     * Called when a previously created loader has finished its load.  Note
     * that normally an application is <em>not</em> allowed to commit fragment
     * transactions while in this call, since it can happen after an
     * activity's state is saved.  See {@link FragmentManager#beginTransaction()
     * FragmentManager.openTransaction()} for further discussion on this.
     * <p>
     * <p>This function is guaranteed to be called prior to the release of
     * the last data that was supplied for this Loader.  At this point
     * you should remove all use of the old data (since it will be released
     * soon), but should not do your own release of the data since its Loader
     * owns it and will take care of that.  The Loader will take care of
     * management of its data so you don't have to.  In particular:
     * <p>
     * <ul>
     * <li> <p>The Loader will monitor for changes to the data, and report
     * them to you through new calls here.  You should not monitor the
     * data yourself.  For example, if the data is a {@link Cursor}
     * and you place it in a {@link CursorAdapter}, use
     * the {@link CursorAdapter#CursorAdapter(Context, * Cursor, int)} constructor <em>without</em> passing
     * in either {@link CursorAdapter#FLAG_AUTO_REQUERY}
     * or {@link CursorAdapter#FLAG_REGISTER_CONTENT_OBSERVER}
     * (that is, use 0 for the flags argument).  This prevents the CursorAdapter
     * from doing its own observing of the Cursor, which is not needed since
     * when a change happens you will get a new Cursor throw another call
     * here.
     * <li> The Loader will release the data once it knows the application
     * is no longer using it.  For example, if the data is
     * a {@link Cursor} from a {@link CursorLoader},
     * you should not call close() on it yourself.  If the Cursor is being placed in a
     * {@link CursorAdapter}, you should use the
     * {@link CursorAdapter#swapCursor(Cursor)}
     * method so that the old Cursor is not closed.
     * </ul>
     * <p>
     * <p>This will always be called from the process's main thread.
     *
     * @param loader The Loader that has finished.
     * @param cursor   The data generated by the Loader.
     */
    @Override
    public void onLoadFinished(@NonNull android.support.v4.content.Loader<Cursor> loader, Cursor cursor) {
        economiaCursorAdapter.refreshData(cursor);
    }

    /**
     * Called when a previously created loader is being reset, and thus
     * making its data unavailable.  The application should at this point
     * remove any references it has to the Loader's data.
     * <p>
     * <p>This will always be called from the process's main thread.
     *
     * @param loader The Loader that is being reset.
     */
    @Override
    public void onLoaderReset(@NonNull android.support.v4.content.Loader<Cursor> loader) {
        economiaCursorAdapter.refreshData(null);
    }


//    @NonNull
//    @Override
//    public Loader<Cursor> onCreateLoader(int id, @Nullable Bundle args) {
//        if (id == CursorLoaderID) {
//            return new android.content.CursorLoader(this, FuncoesContentProvider.FINANCA_URI, DbTabelaFinancas.All_colunas, null, null, null);
//        }
//        return null;
//    }
//
//    @Override
//    public void onLoadFinished(Loader<Cursor> loader, Cursor cursor) {
//        economiaCursorAdapter.refreshData(cursor);
//    }
//
//    @Override
//    public void onLoaderReset(Loader<Cursor> loader) {
//        economiaCursorAdapter.refreshData(null);
//    }
}
